import { Country } from '@/types'

// 全195カ国（国連加盟国193カ国 + バチカン + パレスチナ）
export const countries: Country[] = [
  { code: 'AF', name: { en: 'Afghanistan', ja: 'アフガニスタン', zh: '阿富汗', ko: '아프가니스탄', es: 'Afganistán', fr: 'Afghanistan', de: 'Afghanistan', pt: 'Afeganistão', ru: 'Афганистан', ar: 'أفغانستان' } },
  { code: 'AL', name: { en: 'Albania', ja: 'アルバニア', zh: '阿尔巴尼亚', ko: '알바니아', es: 'Albania', fr: 'Albanie', de: 'Albanien', pt: 'Albânia', ru: 'Албания', ar: 'ألبانيا' } },
  { code: 'DZ', name: { en: 'Algeria', ja: 'アルジェリア', zh: '阿尔及利亚', ko: '알제리', es: 'Argelia', fr: 'Algérie', de: 'Algerien', pt: 'Argélia', ru: 'Алжир', ar: 'الجزائر' } },
  { code: 'AD', name: { en: 'Andorra', ja: 'アンドラ', zh: '安道尔', ko: '안도라', es: 'Andorra', fr: 'Andorre', de: 'Andorra', pt: 'Andorra', ru: 'Андорра', ar: 'أندورا' } },
  { code: 'AO', name: { en: 'Angola', ja: 'アンゴラ', zh: '安哥拉', ko: '앙골라', es: 'Angola', fr: 'Angola', de: 'Angola', pt: 'Angola', ru: 'Ангола', ar: 'أنغولا' } },
  { code: 'AG', name: { en: 'Antigua and Barbuda', ja: 'アンティグア・バーブーダ', zh: '安提瓜和巴布达', ko: '앤티가 바부다', es: 'Antigua y Barbuda', fr: 'Antigua-et-Barbuda', de: 'Antigua und Barbuda', pt: 'Antígua e Barbuda', ru: 'Антигуа и Барбуда', ar: 'أنتيغوا وبربودا' } },
  { code: 'AR', name: { en: 'Argentina', ja: 'アルゼンチン', zh: '阿根廷', ko: '아르헨티나', es: 'Argentina', fr: 'Argentine', de: 'Argentinien', pt: 'Argentina', ru: 'Аргентина', ar: 'الأرجنتين' } },
  { code: 'AM', name: { en: 'Armenia', ja: 'アルメニア', zh: '亚美尼亚', ko: '아르메니아', es: 'Armenia', fr: 'Arménie', de: 'Armenien', pt: 'Arménia', ru: 'Армения', ar: 'أرمينيا' } },
  { code: 'AU', name: { en: 'Australia', ja: 'オーストラリア', zh: '澳大利亚', ko: '호주', es: 'Australia', fr: 'Australie', de: 'Australien', pt: 'Austrália', ru: 'Австралия', ar: 'أستراليا' } },
  { code: 'AT', name: { en: 'Austria', ja: 'オーストリア', zh: '奥地利', ko: '오스트리아', es: 'Austria', fr: 'Autriche', de: 'Österreich', pt: 'Áustria', ru: 'Австрия', ar: 'النمسا' } },
  { code: 'AZ', name: { en: 'Azerbaijan', ja: 'アゼルバイジャン', zh: '阿塞拜疆', ko: '아제르바이잔', es: 'Azerbaiyán', fr: 'Azerbaïdjan', de: 'Aserbaidschan', pt: 'Azerbaijão', ru: 'Азербайджан', ar: 'أذربيجان' } },
  { code: 'BS', name: { en: 'Bahamas', ja: 'バハマ', zh: '巴哈马', ko: '바하마', es: 'Bahamas', fr: 'Bahamas', de: 'Bahamas', pt: 'Bahamas', ru: 'Багамы', ar: 'باهاماس' } },
  { code: 'BH', name: { en: 'Bahrain', ja: 'バーレーン', zh: '巴林', ko: '바레인', es: 'Baréin', fr: 'Bahreïn', de: 'Bahrain', pt: 'Barém', ru: 'Бахрейн', ar: 'البحرين' } },
  { code: 'BD', name: { en: 'Bangladesh', ja: 'バングラデシュ', zh: '孟加拉国', ko: '방글라데시', es: 'Bangladesh', fr: 'Bangladesh', de: 'Bangladesch', pt: 'Bangladesh', ru: 'Бангладеш', ar: 'بنغلاديش' } },
  { code: 'BB', name: { en: 'Barbados', ja: 'バルバドス', zh: '巴巴多斯', ko: '바베이도스', es: 'Barbados', fr: 'Barbade', de: 'Barbados', pt: 'Barbados', ru: 'Барбадос', ar: 'بربادوس' } },
  { code: 'BY', name: { en: 'Belarus', ja: 'ベラルーシ', zh: '白俄罗斯', ko: '벨라루스', es: 'Bielorrusia', fr: 'Biélorussie', de: 'Belarus', pt: 'Bielorrússia', ru: 'Беларусь', ar: 'بيلاروسيا' } },
  { code: 'BE', name: { en: 'Belgium', ja: 'ベルギー', zh: '比利时', ko: '벨기에', es: 'Bélgica', fr: 'Belgique', de: 'Belgien', pt: 'Bélgica', ru: 'Бельгия', ar: 'بلجيكا' } },
  { code: 'BZ', name: { en: 'Belize', ja: 'ベリーズ', zh: '伯利兹', ko: '벨리즈', es: 'Belice', fr: 'Belize', de: 'Belize', pt: 'Belize', ru: 'Белиз', ar: 'بليز' } },
  { code: 'BJ', name: { en: 'Benin', ja: 'ベナン', zh: '贝宁', ko: '베냉', es: 'Benín', fr: 'Bénin', de: 'Benin', pt: 'Benim', ru: 'Бенин', ar: 'بنين' } },
  { code: 'BT', name: { en: 'Bhutan', ja: 'ブータン', zh: '不丹', ko: '부탄', es: 'Bután', fr: 'Bhoutan', de: 'Bhutan', pt: 'Butão', ru: 'Бутан', ar: 'بوتان' } },
  { code: 'BO', name: { en: 'Bolivia', ja: 'ボリビア', zh: '玻利维亚', ko: '볼리비아', es: 'Bolivia', fr: 'Bolivie', de: 'Bolivien', pt: 'Bolívia', ru: 'Боливия', ar: 'بوليفيا' } },
  { code: 'BA', name: { en: 'Bosnia and Herzegovina', ja: 'ボスニア・ヘルツェゴビナ', zh: '波斯尼亚和黑塞哥维那', ko: '보스니아 헤르체고비나', es: 'Bosnia y Herzegovina', fr: 'Bosnie-Herzégovine', de: 'Bosnien und Herzegowina', pt: 'Bósnia e Herzegovina', ru: 'Босния и Герцеговина', ar: 'البوسنة والهرسك' } },
  { code: 'BW', name: { en: 'Botswana', ja: 'ボツワナ', zh: '博茨瓦纳', ko: '보츠와나', es: 'Botsuana', fr: 'Botswana', de: 'Botswana', pt: 'Botsuana', ru: 'Ботсвана', ar: 'بوتسوانا' } },
  { code: 'BR', name: { en: 'Brazil', ja: 'ブラジル', zh: '巴西', ko: '브라질', es: 'Brasil', fr: 'Brésil', de: 'Brasilien', pt: 'Brasil', ru: 'Бразилия', ar: 'البرازيل' } },
  { code: 'BN', name: { en: 'Brunei', ja: 'ブルネイ', zh: '文莱', ko: '브루나이', es: 'Brunéi', fr: 'Brunei', de: 'Brunei', pt: 'Brunei', ru: 'Бруней', ar: 'بروناي' } },
  { code: 'BG', name: { en: 'Bulgaria', ja: 'ブルガリア', zh: '保加利亚', ko: '불가리아', es: 'Bulgaria', fr: 'Bulgarie', de: 'Bulgarien', pt: 'Bulgária', ru: 'Болгария', ar: 'بلغاريا' } },
  { code: 'BF', name: { en: 'Burkina Faso', ja: 'ブルキナファソ', zh: '布基纳法索', ko: '부르키나파소', es: 'Burkina Faso', fr: 'Burkina Faso', de: 'Burkina Faso', pt: 'Burquina Faso', ru: 'Буркина-Фасо', ar: 'بوركينا فاسو' } },
  { code: 'BI', name: { en: 'Burundi', ja: 'ブルンジ', zh: '布隆迪', ko: '부룬디', es: 'Burundi', fr: 'Burundi', de: 'Burundi', pt: 'Burundi', ru: 'Бурунди', ar: 'بوروندي' } },
  { code: 'KH', name: { en: 'Cambodia', ja: 'カンボジア', zh: '柬埔寨', ko: '캄보디아', es: 'Camboya', fr: 'Cambodge', de: 'Kambodscha', pt: 'Camboja', ru: 'Камбоджа', ar: 'كمبوديا' } },
  { code: 'CM', name: { en: 'Cameroon', ja: 'カメルーン', zh: '喀麦隆', ko: '카메룬', es: 'Camerún', fr: 'Cameroun', de: 'Kamerun', pt: 'Camarões', ru: 'Камерун', ar: 'الكاميرون' } },
  { code: 'CA', name: { en: 'Canada', ja: 'カナダ', zh: '加拿大', ko: '캐나다', es: 'Canadá', fr: 'Canada', de: 'Kanada', pt: 'Canadá', ru: 'Канада', ar: 'كندا' } },
  { code: 'CV', name: { en: 'Cape Verde', ja: 'カーボベルデ', zh: '佛得角', ko: '카보베르데', es: 'Cabo Verde', fr: 'Cap-Vert', de: 'Kap Verde', pt: 'Cabo Verde', ru: 'Кабо-Верде', ar: 'الرأس الأخضر' } },
  { code: 'CF', name: { en: 'Central African Republic', ja: '中央アフリカ', zh: '中非共和国', ko: '중앙아프리카 공화국', es: 'República Centroafricana', fr: 'République centrafricaine', de: 'Zentralafrikanische Republik', pt: 'República Centro-Africana', ru: 'ЦАР', ar: 'جمهورية أفريقيا الوسطى' } },
  { code: 'TD', name: { en: 'Chad', ja: 'チャド', zh: '乍得', ko: '차드', es: 'Chad', fr: 'Tchad', de: 'Tschad', pt: 'Chade', ru: 'Чад', ar: 'تشاد' } },
  { code: 'CL', name: { en: 'Chile', ja: 'チリ', zh: '智利', ko: '칠레', es: 'Chile', fr: 'Chili', de: 'Chile', pt: 'Chile', ru: 'Чили', ar: 'تشيلي' } },
  { code: 'CN', name: { en: 'China', ja: '中国', zh: '中国', ko: '중국', es: 'China', fr: 'Chine', de: 'China', pt: 'China', ru: 'Китай', ar: 'الصين' } },
  { code: 'CO', name: { en: 'Colombia', ja: 'コロンビア', zh: '哥伦比亚', ko: '콜롬비아', es: 'Colombia', fr: 'Colombie', de: 'Kolumbien', pt: 'Colômbia', ru: 'Колумбия', ar: 'كولومبيا' } },
  { code: 'KM', name: { en: 'Comoros', ja: 'コモロ', zh: '科摩罗', ko: '코모로', es: 'Comoras', fr: 'Comores', de: 'Komoren', pt: 'Comores', ru: 'Коморы', ar: 'جزر القمر' } },
  { code: 'CG', name: { en: 'Congo', ja: 'コンゴ共和国', zh: '刚果共和国', ko: '콩고 공화국', es: 'Congo', fr: 'Congo', de: 'Kongo', pt: 'Congo', ru: 'Республика Конго', ar: 'الكونغو' } },
  { code: 'CR', name: { en: 'Costa Rica', ja: 'コスタリカ', zh: '哥斯达黎加', ko: '코스타리카', es: 'Costa Rica', fr: 'Costa Rica', de: 'Costa Rica', pt: 'Costa Rica', ru: 'Коста-Рика', ar: 'كوستاريكا' } },
  { code: 'HR', name: { en: 'Croatia', ja: 'クロアチア', zh: '克罗地亚', ko: '크로아티아', es: 'Croacia', fr: 'Croatie', de: 'Kroatien', pt: 'Croácia', ru: 'Хорватия', ar: 'كرواتيا' } },
  { code: 'CU', name: { en: 'Cuba', ja: 'キューバ', zh: '古巴', ko: '쿠바', es: 'Cuba', fr: 'Cuba', de: 'Kuba', pt: 'Cuba', ru: 'Куба', ar: 'كوبا' } },
  { code: 'CY', name: { en: 'Cyprus', ja: 'キプロス', zh: '塞浦路斯', ko: '키프로스', es: 'Chipre', fr: 'Chypre', de: 'Zypern', pt: 'Chipre', ru: 'Кипр', ar: 'قبرص' } },
  { code: 'CZ', name: { en: 'Czech Republic', ja: 'チェコ', zh: '捷克', ko: '체코', es: 'República Checa', fr: 'République tchèque', de: 'Tschechien', pt: 'República Checa', ru: 'Чехия', ar: 'التشيك' } },
  { code: 'DK', name: { en: 'Denmark', ja: 'デンマーク', zh: '丹麦', ko: '덴마크', es: 'Dinamarca', fr: 'Danemark', de: 'Dänemark', pt: 'Dinamarca', ru: 'Дания', ar: 'الدنمارك' } },
  { code: 'DJ', name: { en: 'Djibouti', ja: 'ジブチ', zh: '吉布提', ko: '지부티', es: 'Yibuti', fr: 'Djibouti', de: 'Dschibuti', pt: 'Djibuti', ru: 'Джибути', ar: 'جيبوتي' } },
  { code: 'DM', name: { en: 'Dominica', ja: 'ドミニカ国', zh: '多米尼克', ko: '도미니카 연방', es: 'Dominica', fr: 'Dominique', de: 'Dominica', pt: 'Dominica', ru: 'Доминика', ar: 'دومينيكا' } },
  { code: 'DO', name: { en: 'Dominican Republic', ja: 'ドミニカ共和国', zh: '多米尼加共和国', ko: '도미니카 공화국', es: 'República Dominicana', fr: 'République dominicaine', de: 'Dominikanische Republik', pt: 'República Dominicana', ru: 'Доминиканская Республика', ar: 'جمهورية الدومينيكان' } },
  { code: 'EC', name: { en: 'Ecuador', ja: 'エクアドル', zh: '厄瓜多尔', ko: '에콰도르', es: 'Ecuador', fr: 'Équateur', de: 'Ecuador', pt: 'Equador', ru: 'Эквадор', ar: 'الإكوادور' } },
  { code: 'EG', name: { en: 'Egypt', ja: 'エジプト', zh: '埃及', ko: '이집트', es: 'Egipto', fr: 'Égypte', de: 'Ägypten', pt: 'Egito', ru: 'Египет', ar: 'مصر' } },
  { code: 'SV', name: { en: 'El Salvador', ja: 'エルサルバドル', zh: '萨尔瓦多', ko: '엘살바도르', es: 'El Salvador', fr: 'Salvador', de: 'El Salvador', pt: 'El Salvador', ru: 'Сальвадор', ar: 'السلفادور' } },
  { code: 'GQ', name: { en: 'Equatorial Guinea', ja: '赤道ギニア', zh: '赤道几内亚', ko: '적도 기니', es: 'Guinea Ecuatorial', fr: 'Guinée équatoriale', de: 'Äquatorialguinea', pt: 'Guiné Equatorial', ru: 'Экваториальная Гвинея', ar: 'غينيا الاستوائية' } },
  { code: 'ER', name: { en: 'Eritrea', ja: 'エリトリア', zh: '厄立特里亚', ko: '에리트레아', es: 'Eritrea', fr: 'Érythrée', de: 'Eritrea', pt: 'Eritreia', ru: 'Эритрея', ar: 'إريتريا' } },
  { code: 'EE', name: { en: 'Estonia', ja: 'エストニア', zh: '爱沙尼亚', ko: '에스토니아', es: 'Estonia', fr: 'Estonie', de: 'Estland', pt: 'Estónia', ru: 'Эстония', ar: 'إستونيا' } },
  { code: 'SZ', name: { en: 'Eswatini', ja: 'エスワティニ', zh: '斯威士兰', ko: '에스와티니', es: 'Esuatini', fr: 'Eswatini', de: 'Eswatini', pt: 'Essuatíni', ru: 'Эсватини', ar: 'إسواتيني' } },
  { code: 'ET', name: { en: 'Ethiopia', ja: 'エチオピア', zh: '埃塞俄比亚', ko: '에티오피아', es: 'Etiopía', fr: 'Éthiopie', de: 'Äthiopien', pt: 'Etiópia', ru: 'Эфиопия', ar: 'إثيوبيا' } },
  { code: 'FJ', name: { en: 'Fiji', ja: 'フィジー', zh: '斐济', ko: '피지', es: 'Fiyi', fr: 'Fidji', de: 'Fidschi', pt: 'Fiji', ru: 'Фиджи', ar: 'فيجي' } },
  { code: 'FI', name: { en: 'Finland', ja: 'フィンランド', zh: '芬兰', ko: '핀란드', es: 'Finlandia', fr: 'Finlande', de: 'Finnland', pt: 'Finlândia', ru: 'Финляндия', ar: 'فنلندا' } },
  { code: 'FR', name: { en: 'France', ja: 'フランス', zh: '法国', ko: '프랑스', es: 'Francia', fr: 'France', de: 'Frankreich', pt: 'França', ru: 'Франция', ar: 'فرنسا' } },
  { code: 'GA', name: { en: 'Gabon', ja: 'ガボン', zh: '加蓬', ko: '가봉', es: 'Gabón', fr: 'Gabon', de: 'Gabun', pt: 'Gabão', ru: 'Габон', ar: 'الغابون' } },
  { code: 'GM', name: { en: 'Gambia', ja: 'ガンビア', zh: '冈比亚', ko: '감비아', es: 'Gambia', fr: 'Gambie', de: 'Gambia', pt: 'Gâmbia', ru: 'Гамбия', ar: 'غامبيا' } },
  { code: 'GE', name: { en: 'Georgia', ja: 'ジョージア', zh: '格鲁吉亚', ko: '조지아', es: 'Georgia', fr: 'Géorgie', de: 'Georgien', pt: 'Geórgia', ru: 'Грузия', ar: 'جورجيا' } },
  { code: 'DE', name: { en: 'Germany', ja: 'ドイツ', zh: '德国', ko: '독일', es: 'Alemania', fr: 'Allemagne', de: 'Deutschland', pt: 'Alemanha', ru: 'Германия', ar: 'ألمانيا' } },
  { code: 'GH', name: { en: 'Ghana', ja: 'ガーナ', zh: '加纳', ko: '가나', es: 'Ghana', fr: 'Ghana', de: 'Ghana', pt: 'Gana', ru: 'Гана', ar: 'غانا' } },
  { code: 'GR', name: { en: 'Greece', ja: 'ギリシャ', zh: '希腊', ko: '그리스', es: 'Grecia', fr: 'Grèce', de: 'Griechenland', pt: 'Grécia', ru: 'Греция', ar: 'اليونان' } },
  { code: 'GD', name: { en: 'Grenada', ja: 'グレナダ', zh: '格林纳达', ko: '그레나다', es: 'Granada', fr: 'Grenade', de: 'Grenada', pt: 'Granada', ru: 'Гренада', ar: 'غرينادا' } },
  { code: 'GT', name: { en: 'Guatemala', ja: 'グアテマラ', zh: '危地马拉', ko: '과테말라', es: 'Guatemala', fr: 'Guatemala', de: 'Guatemala', pt: 'Guatemala', ru: 'Гватемала', ar: 'غواتيمالا' } },
  { code: 'GN', name: { en: 'Guinea', ja: 'ギニア', zh: '几内亚', ko: '기니', es: 'Guinea', fr: 'Guinée', de: 'Guinea', pt: 'Guiné', ru: 'Гвинея', ar: 'غينيا' } },
  { code: 'GW', name: { en: 'Guinea-Bissau', ja: 'ギニアビサウ', zh: '几内亚比绍', ko: '기니비사우', es: 'Guinea-Bisáu', fr: 'Guinée-Bissau', de: 'Guinea-Bissau', pt: 'Guiné-Bissau', ru: 'Гвинея-Бисау', ar: 'غينيا بيساو' } },
  { code: 'GY', name: { en: 'Guyana', ja: 'ガイアナ', zh: '圭亚那', ko: '가이아나', es: 'Guyana', fr: 'Guyana', de: 'Guyana', pt: 'Guiana', ru: 'Гайана', ar: 'غيانا' } },
  { code: 'HT', name: { en: 'Haiti', ja: 'ハイチ', zh: '海地', ko: '아이티', es: 'Haití', fr: 'Haïti', de: 'Haiti', pt: 'Haiti', ru: 'Гаити', ar: 'هايتي' } },
  { code: 'HN', name: { en: 'Honduras', ja: 'ホンジュラス', zh: '洪都拉斯', ko: '온두라스', es: 'Honduras', fr: 'Honduras', de: 'Honduras', pt: 'Honduras', ru: 'Гондурас', ar: 'هندوراس' } },
  { code: 'HU', name: { en: 'Hungary', ja: 'ハンガリー', zh: '匈牙利', ko: '헝가리', es: 'Hungría', fr: 'Hongrie', de: 'Ungarn', pt: 'Hungria', ru: 'Венгрия', ar: 'المجر' } },
  { code: 'IS', name: { en: 'Iceland', ja: 'アイスランド', zh: '冰岛', ko: '아이슬란드', es: 'Islandia', fr: 'Islande', de: 'Island', pt: 'Islândia', ru: 'Исландия', ar: 'آيسلندا' } },
  { code: 'IN', name: { en: 'India', ja: 'インド', zh: '印度', ko: '인도', es: 'India', fr: 'Inde', de: 'Indien', pt: 'Índia', ru: 'Индия', ar: 'الهند' } },
  { code: 'ID', name: { en: 'Indonesia', ja: 'インドネシア', zh: '印度尼西亚', ko: '인도네시아', es: 'Indonesia', fr: 'Indonésie', de: 'Indonesien', pt: 'Indonésia', ru: 'Индонезия', ar: 'إندونيسيا' } },
  { code: 'IR', name: { en: 'Iran', ja: 'イラン', zh: '伊朗', ko: '이란', es: 'Irán', fr: 'Iran', de: 'Iran', pt: 'Irão', ru: 'Иран', ar: 'إيران' } },
  { code: 'IQ', name: { en: 'Iraq', ja: 'イラク', zh: '伊拉克', ko: '이라크', es: 'Irak', fr: 'Irak', de: 'Irak', pt: 'Iraque', ru: 'Ирак', ar: 'العراق' } },
  { code: 'IE', name: { en: 'Ireland', ja: 'アイルランド', zh: '爱尔兰', ko: '아일랜드', es: 'Irlanda', fr: 'Irlande', de: 'Irland', pt: 'Irlanda', ru: 'Ирландия', ar: 'أيرلندا' } },
  { code: 'IL', name: { en: 'Israel', ja: 'イスラエル', zh: '以色列', ko: '이스라엘', es: 'Israel', fr: 'Israël', de: 'Israel', pt: 'Israel', ru: 'Израиль', ar: 'إسرائيل' } },
  { code: 'IT', name: { en: 'Italy', ja: 'イタリア', zh: '意大利', ko: '이탈리아', es: 'Italia', fr: 'Italie', de: 'Italien', pt: 'Itália', ru: 'Италия', ar: 'إيطاليا' } },
  { code: 'JM', name: { en: 'Jamaica', ja: 'ジャマイカ', zh: '牙买加', ko: '자메이카', es: 'Jamaica', fr: 'Jamaïque', de: 'Jamaika', pt: 'Jamaica', ru: 'Ямайка', ar: 'جامايكا' } },
  { code: 'JP', name: { en: 'Japan', ja: '日本', zh: '日本', ko: '일본', es: 'Japón', fr: 'Japon', de: 'Japan', pt: 'Japão', ru: 'Япония', ar: 'اليابان' } },
  { code: 'JO', name: { en: 'Jordan', ja: 'ヨルダン', zh: '约旦', ko: '요르단', es: 'Jordania', fr: 'Jordanie', de: 'Jordanien', pt: 'Jordânia', ru: 'Иордания', ar: 'الأردن' } },
  { code: 'KZ', name: { en: 'Kazakhstan', ja: 'カザフスタン', zh: '哈萨克斯坦', ko: '카자흐스탄', es: 'Kazajistán', fr: 'Kazakhstan', de: 'Kasachstan', pt: 'Cazaquistão', ru: 'Казахстан', ar: 'كازاخستان' } },
  { code: 'KE', name: { en: 'Kenya', ja: 'ケニア', zh: '肯尼亚', ko: '케냐', es: 'Kenia', fr: 'Kenya', de: 'Kenia', pt: 'Quénia', ru: 'Кения', ar: 'كينيا' } },
  { code: 'KI', name: { en: 'Kiribati', ja: 'キリバス', zh: '基里巴斯', ko: '키리바시', es: 'Kiribati', fr: 'Kiribati', de: 'Kiribati', pt: 'Kiribati', ru: 'Кирибати', ar: 'كيريباتي' } },
  { code: 'KW', name: { en: 'Kuwait', ja: 'クウェート', zh: '科威特', ko: '쿠웨이트', es: 'Kuwait', fr: 'Koweït', de: 'Kuwait', pt: 'Kuwait', ru: 'Кувейт', ar: 'الكويت' } },
  { code: 'KG', name: { en: 'Kyrgyzstan', ja: 'キルギス', zh: '吉尔吉斯斯坦', ko: '키르기스스탄', es: 'Kirguistán', fr: 'Kirghizistan', de: 'Kirgisistan', pt: 'Quirguistão', ru: 'Киргизия', ar: 'قيرغيزستان' } },
  { code: 'LA', name: { en: 'Laos', ja: 'ラオス', zh: '老挝', ko: '라오스', es: 'Laos', fr: 'Laos', de: 'Laos', pt: 'Laos', ru: 'Лаос', ar: 'لاوس' } },
  { code: 'LV', name: { en: 'Latvia', ja: 'ラトビア', zh: '拉脱维亚', ko: '라트비아', es: 'Letonia', fr: 'Lettonie', de: 'Lettland', pt: 'Letónia', ru: 'Латвия', ar: 'لاتفيا' } },
  { code: 'LB', name: { en: 'Lebanon', ja: 'レバノン', zh: '黎巴嫩', ko: '레바논', es: 'Líbano', fr: 'Liban', de: 'Libanon', pt: 'Líbano', ru: 'Ливан', ar: 'لبنان' } },
  { code: 'LS', name: { en: 'Lesotho', ja: 'レソト', zh: '莱索托', ko: '레소토', es: 'Lesoto', fr: 'Lesotho', de: 'Lesotho', pt: 'Lesoto', ru: 'Лесото', ar: 'ليسوتو' } },
  { code: 'LR', name: { en: 'Liberia', ja: 'リベリア', zh: '利比里亚', ko: '라이베리아', es: 'Liberia', fr: 'Libéria', de: 'Liberia', pt: 'Libéria', ru: 'Либерия', ar: 'ليبيريا' } },
  { code: 'LY', name: { en: 'Libya', ja: 'リビア', zh: '利比亚', ko: '리비아', es: 'Libia', fr: 'Libye', de: 'Libyen', pt: 'Líbia', ru: 'Ливия', ar: 'ليبيا' } },
  { code: 'LI', name: { en: 'Liechtenstein', ja: 'リヒテンシュタイン', zh: '列支敦士登', ko: '리히텐슈타인', es: 'Liechtenstein', fr: 'Liechtenstein', de: 'Liechtenstein', pt: 'Listenstaine', ru: 'Лихтенштейн', ar: 'ليختنشتاين' } },
  { code: 'LT', name: { en: 'Lithuania', ja: 'リトアニア', zh: '立陶宛', ko: '리투아니아', es: 'Lituania', fr: 'Lituanie', de: 'Litauen', pt: 'Lituânia', ru: 'Литва', ar: 'ليتوانيا' } },
  { code: 'LU', name: { en: 'Luxembourg', ja: 'ルクセンブルク', zh: '卢森堡', ko: '룩셈부르크', es: 'Luxemburgo', fr: 'Luxembourg', de: 'Luxemburg', pt: 'Luxemburgo', ru: 'Люксембург', ar: 'لوكسمبورغ' } },
  { code: 'MG', name: { en: 'Madagascar', ja: 'マダガスカル', zh: '马达加斯加', ko: '마다가스카르', es: 'Madagascar', fr: 'Madagascar', de: 'Madagaskar', pt: 'Madagáscar', ru: 'Мадагаскар', ar: 'مدغشقر' } },
  { code: 'MW', name: { en: 'Malawi', ja: 'マラウイ', zh: '马拉维', ko: '말라위', es: 'Malaui', fr: 'Malawi', de: 'Malawi', pt: 'Malawi', ru: 'Малави', ar: 'ملاوي' } },
  { code: 'MY', name: { en: 'Malaysia', ja: 'マレーシア', zh: '马来西亚', ko: '말레이시아', es: 'Malasia', fr: 'Malaisie', de: 'Malaysia', pt: 'Malásia', ru: 'Малайзия', ar: 'ماليزيا' } },
  { code: 'MV', name: { en: 'Maldives', ja: 'モルディブ', zh: '马尔代夫', ko: '몰디브', es: 'Maldivas', fr: 'Maldives', de: 'Malediven', pt: 'Maldivas', ru: 'Мальдивы', ar: 'جزر المالديف' } },
  { code: 'ML', name: { en: 'Mali', ja: 'マリ', zh: '马里', ko: '말리', es: 'Malí', fr: 'Mali', de: 'Mali', pt: 'Mali', ru: 'Мали', ar: 'مالي' } },
  { code: 'MT', name: { en: 'Malta', ja: 'マルタ', zh: '马耳他', ko: '몰타', es: 'Malta', fr: 'Malte', de: 'Malta', pt: 'Malta', ru: 'Мальта', ar: 'مالطا' } },
  { code: 'MH', name: { en: 'Marshall Islands', ja: 'マーシャル諸島', zh: '马绍尔群岛', ko: '마셜 제도', es: 'Islas Marshall', fr: 'Îles Marshall', de: 'Marshallinseln', pt: 'Ilhas Marshall', ru: 'Маршалловы Острова', ar: 'جزر مارشال' } },
  { code: 'MR', name: { en: 'Mauritania', ja: 'モーリタニア', zh: '毛里塔尼亚', ko: '모리타니', es: 'Mauritania', fr: 'Mauritanie', de: 'Mauretanien', pt: 'Mauritânia', ru: 'Мавритания', ar: 'موريتانيا' } },
  { code: 'MU', name: { en: 'Mauritius', ja: 'モーリシャス', zh: '毛里求斯', ko: '모리셔스', es: 'Mauricio', fr: 'Maurice', de: 'Mauritius', pt: 'Maurícia', ru: 'Маврикий', ar: 'موريشيوس' } },
  { code: 'MX', name: { en: 'Mexico', ja: 'メキシコ', zh: '墨西哥', ko: '멕시코', es: 'México', fr: 'Mexique', de: 'Mexiko', pt: 'México', ru: 'Мексика', ar: 'المكسيك' } },
  { code: 'FM', name: { en: 'Micronesia', ja: 'ミクロネシア', zh: '密克罗尼西亚', ko: '미크로네시아', es: 'Micronesia', fr: 'Micronésie', de: 'Mikronesien', pt: 'Micronésia', ru: 'Микронезия', ar: 'ميكرونيزيا' } },
  { code: 'MD', name: { en: 'Moldova', ja: 'モルドバ', zh: '摩尔多瓦', ko: '몰도바', es: 'Moldavia', fr: 'Moldavie', de: 'Moldau', pt: 'Moldávia', ru: 'Молдавия', ar: 'مولدوفا' } },
  { code: 'MC', name: { en: 'Monaco', ja: 'モナコ', zh: '摩纳哥', ko: '모나코', es: 'Mónaco', fr: 'Monaco', de: 'Monaco', pt: 'Mónaco', ru: 'Монако', ar: 'موناكو' } },
  { code: 'MN', name: { en: 'Mongolia', ja: 'モンゴル', zh: '蒙古', ko: '몽골', es: 'Mongolia', fr: 'Mongolie', de: 'Mongolei', pt: 'Mongólia', ru: 'Монголия', ar: 'منغوليا' } },
  { code: 'ME', name: { en: 'Montenegro', ja: 'モンテネグロ', zh: '黑山', ko: '몬테네그로', es: 'Montenegro', fr: 'Monténégro', de: 'Montenegro', pt: 'Montenegro', ru: 'Черногория', ar: 'الجبل الأسود' } },
  { code: 'MA', name: { en: 'Morocco', ja: 'モロッコ', zh: '摩洛哥', ko: '모로코', es: 'Marruecos', fr: 'Maroc', de: 'Marokko', pt: 'Marrocos', ru: 'Марокко', ar: 'المغرب' } },
  { code: 'MZ', name: { en: 'Mozambique', ja: 'モザンビーク', zh: '莫桑比克', ko: '모잠비크', es: 'Mozambique', fr: 'Mozambique', de: 'Mosambik', pt: 'Moçambique', ru: 'Мозамбик', ar: 'موزمبيق' } },
  { code: 'MM', name: { en: 'Myanmar', ja: 'ミャンマー', zh: '缅甸', ko: '미얀마', es: 'Myanmar', fr: 'Myanmar', de: 'Myanmar', pt: 'Myanmar', ru: 'Мьянма', ar: 'ميانمار' } },
  { code: 'NA', name: { en: 'Namibia', ja: 'ナミビア', zh: '纳米比亚', ko: '나미비아', es: 'Namibia', fr: 'Namibie', de: 'Namibia', pt: 'Namíbia', ru: 'Намибия', ar: 'ناميبيا' } },
  { code: 'NR', name: { en: 'Nauru', ja: 'ナウル', zh: '瑙鲁', ko: '나우루', es: 'Nauru', fr: 'Nauru', de: 'Nauru', pt: 'Nauru', ru: 'Науру', ar: 'ناورو' } },
  { code: 'NP', name: { en: 'Nepal', ja: 'ネパール', zh: '尼泊尔', ko: '네팔', es: 'Nepal', fr: 'Népal', de: 'Nepal', pt: 'Nepal', ru: 'Непал', ar: 'نيبال' } },
  { code: 'NL', name: { en: 'Netherlands', ja: 'オランダ', zh: '荷兰', ko: '네덜란드', es: 'Países Bajos', fr: 'Pays-Bas', de: 'Niederlande', pt: 'Países Baixos', ru: 'Нидерланды', ar: 'هولندا' } },
  { code: 'NZ', name: { en: 'New Zealand', ja: 'ニュージーランド', zh: '新西兰', ko: '뉴질랜드', es: 'Nueva Zelanda', fr: 'Nouvelle-Zélande', de: 'Neuseeland', pt: 'Nova Zelândia', ru: 'Новая Зеландия', ar: 'نيوزيلندا' } },
  { code: 'NI', name: { en: 'Nicaragua', ja: 'ニカラグア', zh: '尼加拉瓜', ko: '니카라과', es: 'Nicaragua', fr: 'Nicaragua', de: 'Nicaragua', pt: 'Nicarágua', ru: 'Никарагуа', ar: 'نيكاراغوا' } },
  { code: 'NE', name: { en: 'Niger', ja: 'ニジェール', zh: '尼日尔', ko: '니제르', es: 'Níger', fr: 'Niger', de: 'Niger', pt: 'Níger', ru: 'Нигер', ar: 'النيجر' } },
  { code: 'NG', name: { en: 'Nigeria', ja: 'ナイジェリア', zh: '尼日利亚', ko: '나이지리아', es: 'Nigeria', fr: 'Nigeria', de: 'Nigeria', pt: 'Nigéria', ru: 'Нигерия', ar: 'نيجيريا' } },
  { code: 'KP', name: { en: 'North Korea', ja: '北朝鮮', zh: '朝鲜', ko: '조선민주주의인민공화국', es: 'Corea del Norte', fr: 'Corée du Nord', de: 'Nordkorea', pt: 'Coreia do Norte', ru: 'КНДР', ar: 'كوريا الشمالية' } },
  { code: 'MK', name: { en: 'North Macedonia', ja: '北マケドニア', zh: '北马其顿', ko: '북마케도니아', es: 'Macedonia del Norte', fr: 'Macédoine du Nord', de: 'Nordmazedonien', pt: 'Macedónia do Norte', ru: 'Северная Македония', ar: 'مقدونيا الشمالية' } },
  { code: 'NO', name: { en: 'Norway', ja: 'ノルウェー', zh: '挪威', ko: '노르웨이', es: 'Noruega', fr: 'Norvège', de: 'Norwegen', pt: 'Noruega', ru: 'Норвегия', ar: 'النرويج' } },
  { code: 'OM', name: { en: 'Oman', ja: 'オマーン', zh: '阿曼', ko: '오만', es: 'Omán', fr: 'Oman', de: 'Oman', pt: 'Omã', ru: 'Оман', ar: 'عمان' } },
  { code: 'PK', name: { en: 'Pakistan', ja: 'パキスタン', zh: '巴基斯坦', ko: '파키스탄', es: 'Pakistán', fr: 'Pakistan', de: 'Pakistan', pt: 'Paquistão', ru: 'Пакистан', ar: 'باكستان' } },
  { code: 'PW', name: { en: 'Palau', ja: 'パラオ', zh: '帕劳', ko: '팔라우', es: 'Palaos', fr: 'Palaos', de: 'Palau', pt: 'Palau', ru: 'Палау', ar: 'بالاو' } },
  { code: 'PA', name: { en: 'Panama', ja: 'パナマ', zh: '巴拿马', ko: '파나마', es: 'Panamá', fr: 'Panama', de: 'Panama', pt: 'Panamá', ru: 'Панама', ar: 'بنما' } },
  { code: 'PG', name: { en: 'Papua New Guinea', ja: 'パプアニューギニア', zh: '巴布亚新几内亚', ko: '파푸아뉴기니', es: 'Papúa Nueva Guinea', fr: 'Papouasie-Nouvelle-Guinée', de: 'Papua-Neuguinea', pt: 'Papua-Nova Guiné', ru: 'Папуа — Новая Гвинея', ar: 'بابوا غينيا الجديدة' } },
  { code: 'PY', name: { en: 'Paraguay', ja: 'パラグアイ', zh: '巴拉圭', ko: '파라과이', es: 'Paraguay', fr: 'Paraguay', de: 'Paraguay', pt: 'Paraguai', ru: 'Парагвай', ar: 'باراغواي' } },
  { code: 'PE', name: { en: 'Peru', ja: 'ペルー', zh: '秘鲁', ko: '페루', es: 'Perú', fr: 'Pérou', de: 'Peru', pt: 'Peru', ru: 'Перу', ar: 'بيرو' } },
  { code: 'PH', name: { en: 'Philippines', ja: 'フィリピン', zh: '菲律宾', ko: '필리핀', es: 'Filipinas', fr: 'Philippines', de: 'Philippinen', pt: 'Filipinas', ru: 'Филиппины', ar: 'الفلبين' } },
  { code: 'PL', name: { en: 'Poland', ja: 'ポーランド', zh: '波兰', ko: '폴란드', es: 'Polonia', fr: 'Pologne', de: 'Polen', pt: 'Polónia', ru: 'Польша', ar: 'بولندا' } },
  { code: 'PT', name: { en: 'Portugal', ja: 'ポルトガル', zh: '葡萄牙', ko: '포르투갈', es: 'Portugal', fr: 'Portugal', de: 'Portugal', pt: 'Portugal', ru: 'Португалия', ar: 'البرتغال' } },
  { code: 'QA', name: { en: 'Qatar', ja: 'カタール', zh: '卡塔尔', ko: '카타르', es: 'Catar', fr: 'Qatar', de: 'Katar', pt: 'Catar', ru: 'Катар', ar: 'قطر' } },
  { code: 'RO', name: { en: 'Romania', ja: 'ルーマニア', zh: '罗马尼亚', ko: '루마니아', es: 'Rumania', fr: 'Roumanie', de: 'Rumänien', pt: 'Roménia', ru: 'Румыния', ar: 'رومانيا' } },
  { code: 'RU', name: { en: 'Russia', ja: 'ロシア', zh: '俄罗斯', ko: '러시아', es: 'Rusia', fr: 'Russie', de: 'Russland', pt: 'Rússia', ru: 'Россия', ar: 'روسيا' } },
  { code: 'RW', name: { en: 'Rwanda', ja: 'ルワンダ', zh: '卢旺达', ko: '르완다', es: 'Ruanda', fr: 'Rwanda', de: 'Ruanda', pt: 'Ruanda', ru: 'Руанда', ar: 'رواندا' } },
  { code: 'KN', name: { en: 'Saint Kitts and Nevis', ja: 'セントクリストファー・ネイビス', zh: '圣基茨和尼维斯', ko: '세인트키츠 네비스', es: 'San Cristóbal y Nieves', fr: 'Saint-Christophe-et-Niévès', de: 'St. Kitts und Nevis', pt: 'São Cristóvão e Neves', ru: 'Сент-Китс и Невис', ar: 'سانت كيتس ونيفيس' } },
  { code: 'LC', name: { en: 'Saint Lucia', ja: 'セントルシア', zh: '圣卢西亚', ko: '세인트루시아', es: 'Santa Lucía', fr: 'Sainte-Lucie', de: 'St. Lucia', pt: 'Santa Lúcia', ru: 'Сент-Люсия', ar: 'سانت لوسيا' } },
  { code: 'VC', name: { en: 'Saint Vincent and the Grenadines', ja: 'セントビンセント・グレナディーン', zh: '圣文森特和格林纳丁斯', ko: '세인트빈센트 그레나딘', es: 'San Vicente y las Granadinas', fr: 'Saint-Vincent-et-les-Grenadines', de: 'St. Vincent und die Grenadinen', pt: 'São Vicente e Granadinas', ru: 'Сент-Винсент и Гренадины', ar: 'سانت فينسنت والغرينادين' } },
  { code: 'WS', name: { en: 'Samoa', ja: 'サモア', zh: '萨摩亚', ko: '사모아', es: 'Samoa', fr: 'Samoa', de: 'Samoa', pt: 'Samoa', ru: 'Самоа', ar: 'ساموا' } },
  { code: 'SM', name: { en: 'San Marino', ja: 'サンマリノ', zh: '圣马力诺', ko: '산마리노', es: 'San Marino', fr: 'Saint-Marin', de: 'San Marino', pt: 'São Marinho', ru: 'Сан-Марино', ar: 'سان مارينو' } },
  { code: 'ST', name: { en: 'Sao Tome and Principe', ja: 'サントメ・プリンシペ', zh: '圣多美和普林西比', ko: '상투메 프린시페', es: 'Santo Tomé y Príncipe', fr: 'Sao Tomé-et-Principe', de: 'São Tomé und Príncipe', pt: 'São Tomé e Príncipe', ru: 'Сан-Томе и Принсипи', ar: 'ساو تومي وبرينسيب' } },
  { code: 'SA', name: { en: 'Saudi Arabia', ja: 'サウジアラビア', zh: '沙特阿拉伯', ko: '사우디아라비아', es: 'Arabia Saudita', fr: 'Arabie saoudite', de: 'Saudi-Arabien', pt: 'Arábia Saudita', ru: 'Саудовская Аравия', ar: 'السعودية' } },
  { code: 'SN', name: { en: 'Senegal', ja: 'セネガル', zh: '塞内加尔', ko: '세네갈', es: 'Senegal', fr: 'Sénégal', de: 'Senegal', pt: 'Senegal', ru: 'Сенегал', ar: 'السنغال' } },
  { code: 'RS', name: { en: 'Serbia', ja: 'セルビア', zh: '塞尔维亚', ko: '세르비아', es: 'Serbia', fr: 'Serbie', de: 'Serbien', pt: 'Sérvia', ru: 'Сербия', ar: 'صربيا' } },
  { code: 'SC', name: { en: 'Seychelles', ja: 'セーシェル', zh: '塞舌尔', ko: '세이셸', es: 'Seychelles', fr: 'Seychelles', de: 'Seychellen', pt: 'Seychelles', ru: 'Сейшелы', ar: 'سيشل' } },
  { code: 'SL', name: { en: 'Sierra Leone', ja: 'シエラレオネ', zh: '塞拉利昂', ko: '시에라리온', es: 'Sierra Leona', fr: 'Sierra Leone', de: 'Sierra Leone', pt: 'Serra Leoa', ru: 'Сьерра-Леоне', ar: 'سيراليون' } },
  { code: 'SG', name: { en: 'Singapore', ja: 'シンガポール', zh: '新加坡', ko: '싱가포르', es: 'Singapur', fr: 'Singapour', de: 'Singapur', pt: 'Singapura', ru: 'Сингапур', ar: 'سنغافورة' } },
  { code: 'SK', name: { en: 'Slovakia', ja: 'スロバキア', zh: '斯洛伐克', ko: '슬로바키아', es: 'Eslovaquia', fr: 'Slovaquie', de: 'Slowakei', pt: 'Eslováquia', ru: 'Словакия', ar: 'سلوفاكيا' } },
  { code: 'SI', name: { en: 'Slovenia', ja: 'スロベニア', zh: '斯洛文尼亚', ko: '슬로베니아', es: 'Eslovenia', fr: 'Slovénie', de: 'Slowenien', pt: 'Eslovénia', ru: 'Словения', ar: 'سلوفينيا' } },
  { code: 'SB', name: { en: 'Solomon Islands', ja: 'ソロモン諸島', zh: '所罗门群岛', ko: '솔로몬 제도', es: 'Islas Salomón', fr: 'Îles Salomon', de: 'Salomonen', pt: 'Ilhas Salomão', ru: 'Соломоновы Острова', ar: 'جزر سليمان' } },
  { code: 'SO', name: { en: 'Somalia', ja: 'ソマリア', zh: '索马里', ko: '소말리아', es: 'Somalia', fr: 'Somalie', de: 'Somalia', pt: 'Somália', ru: 'Сомали', ar: 'الصومال' } },
  { code: 'ZA', name: { en: 'South Africa', ja: '南アフリカ', zh: '南非', ko: '남아프리카 공화국', es: 'Sudáfrica', fr: 'Afrique du Sud', de: 'Südafrika', pt: 'África do Sul', ru: 'ЮАР', ar: 'جنوب أفريقيا' } },
  { code: 'KR', name: { en: 'South Korea', ja: '韓国', zh: '韩国', ko: '대한민국', es: 'Corea del Sur', fr: 'Corée du Sud', de: 'Südkorea', pt: 'Coreia do Sul', ru: 'Южная Корея', ar: 'كوريا الجنوبية' } },
  { code: 'SS', name: { en: 'South Sudan', ja: '南スーダン', zh: '南苏丹', ko: '남수단', es: 'Sudán del Sur', fr: 'Soudan du Sud', de: 'Südsudan', pt: 'Sudão do Sul', ru: 'Южный Судан', ar: 'جنوب السودان' } },
  { code: 'ES', name: { en: 'Spain', ja: 'スペイン', zh: '西班牙', ko: '스페인', es: 'España', fr: 'Espagne', de: 'Spanien', pt: 'Espanha', ru: 'Испания', ar: 'إسبانيا' } },
  { code: 'LK', name: { en: 'Sri Lanka', ja: 'スリランカ', zh: '斯里兰卡', ko: '스리랑카', es: 'Sri Lanka', fr: 'Sri Lanka', de: 'Sri Lanka', pt: 'Sri Lanca', ru: 'Шри-Ланка', ar: 'سريلانكا' } },
  { code: 'SD', name: { en: 'Sudan', ja: 'スーダン', zh: '苏丹', ko: '수단', es: 'Sudán', fr: 'Soudan', de: 'Sudan', pt: 'Sudão', ru: 'Судан', ar: 'السودان' } },
  { code: 'SR', name: { en: 'Suriname', ja: 'スリナム', zh: '苏里南', ko: '수리남', es: 'Surinam', fr: 'Suriname', de: 'Suriname', pt: 'Suriname', ru: 'Суринам', ar: 'سورينام' } },
  { code: 'SE', name: { en: 'Sweden', ja: 'スウェーデン', zh: '瑞典', ko: '스웨덴', es: 'Suecia', fr: 'Suède', de: 'Schweden', pt: 'Suécia', ru: 'Швеция', ar: 'السويد' } },
  { code: 'CH', name: { en: 'Switzerland', ja: 'スイス', zh: '瑞士', ko: '스위스', es: 'Suiza', fr: 'Suisse', de: 'Schweiz', pt: 'Suíça', ru: 'Швейцария', ar: 'سويسرا' } },
  { code: 'SY', name: { en: 'Syria', ja: 'シリア', zh: '叙利亚', ko: '시리아', es: 'Siria', fr: 'Syrie', de: 'Syrien', pt: 'Síria', ru: 'Сирия', ar: 'سوريا' } },
  { code: 'TJ', name: { en: 'Tajikistan', ja: 'タジキスタン', zh: '塔吉克斯坦', ko: '타지키스탄', es: 'Tayikistán', fr: 'Tadjikistan', de: 'Tadschikistan', pt: 'Tajiquistão', ru: 'Таджикистан', ar: 'طاجيكستان' } },
  { code: 'TZ', name: { en: 'Tanzania', ja: 'タンザニア', zh: '坦桑尼亚', ko: '탄자니아', es: 'Tanzania', fr: 'Tanzanie', de: 'Tansania', pt: 'Tanzânia', ru: 'Танзания', ar: 'تنزانيا' } },
  { code: 'TH', name: { en: 'Thailand', ja: 'タイ', zh: '泰国', ko: '태국', es: 'Tailandia', fr: 'Thaïlande', de: 'Thailand', pt: 'Tailândia', ru: 'Таиланд', ar: 'تايلاند' } },
  { code: 'TL', name: { en: 'Timor-Leste', ja: '東ティモール', zh: '东帝汶', ko: '동티모르', es: 'Timor Oriental', fr: 'Timor oriental', de: 'Osttimor', pt: 'Timor-Leste', ru: 'Восточный Тимор', ar: 'تيمور الشرقية' } },
  { code: 'TG', name: { en: 'Togo', ja: 'トーゴ', zh: '多哥', ko: '토고', es: 'Togo', fr: 'Togo', de: 'Togo', pt: 'Togo', ru: 'Того', ar: 'توغو' } },
  { code: 'TO', name: { en: 'Tonga', ja: 'トンガ', zh: '汤加', ko: '통가', es: 'Tonga', fr: 'Tonga', de: 'Tonga', pt: 'Tonga', ru: 'Тонга', ar: 'تونغا' } },
  { code: 'TT', name: { en: 'Trinidad and Tobago', ja: 'トリニダード・トバゴ', zh: '特立尼达和多巴哥', ko: '트리니다드 토바고', es: 'Trinidad y Tobago', fr: 'Trinité-et-Tobago', de: 'Trinidad und Tobago', pt: 'Trindade e Tobago', ru: 'Тринидад и Тобаго', ar: 'ترينيداد وتوباغو' } },
  { code: 'TN', name: { en: 'Tunisia', ja: 'チュニジア', zh: '突尼斯', ko: '튀니지', es: 'Túnez', fr: 'Tunisie', de: 'Tunesien', pt: 'Tunísia', ru: 'Тунис', ar: 'تونس' } },
  { code: 'TR', name: { en: 'Turkey', ja: 'トルコ', zh: '土耳其', ko: '튀르키예', es: 'Turquía', fr: 'Turquie', de: 'Türkei', pt: 'Turquia', ru: 'Турция', ar: 'تركيا' } },
  { code: 'TM', name: { en: 'Turkmenistan', ja: 'トルクメニスタン', zh: '土库曼斯坦', ko: '투르크메니스탄', es: 'Turkmenistán', fr: 'Turkménistan', de: 'Turkmenistan', pt: 'Turquemenistão', ru: 'Туркменистан', ar: 'تركمانستان' } },
  { code: 'TV', name: { en: 'Tuvalu', ja: 'ツバル', zh: '图瓦卢', ko: '투발루', es: 'Tuvalu', fr: 'Tuvalu', de: 'Tuvalu', pt: 'Tuvalu', ru: 'Тувалу', ar: 'توفالو' } },
  { code: 'UG', name: { en: 'Uganda', ja: 'ウガンダ', zh: '乌干达', ko: '우간다', es: 'Uganda', fr: 'Ouganda', de: 'Uganda', pt: 'Uganda', ru: 'Уганда', ar: 'أوغندا' } },
  { code: 'UA', name: { en: 'Ukraine', ja: 'ウクライナ', zh: '乌克兰', ko: '우크라이나', es: 'Ucrania', fr: 'Ukraine', de: 'Ukraine', pt: 'Ucrânia', ru: 'Украина', ar: 'أوكرانيا' } },
  { code: 'AE', name: { en: 'United Arab Emirates', ja: 'アラブ首長国連邦', zh: '阿联酋', ko: '아랍에미리트', es: 'Emiratos Árabes Unidos', fr: 'Émirats arabes unis', de: 'VAE', pt: 'Emirados Árabes Unidos', ru: 'ОАЭ', ar: 'الإمارات' } },
  { code: 'GB', name: { en: 'United Kingdom', ja: 'イギリス', zh: '英国', ko: '영국', es: 'Reino Unido', fr: 'Royaume-Uni', de: 'Vereinigtes Königreich', pt: 'Reino Unido', ru: 'Великобритания', ar: 'المملكة المتحدة' } },
  { code: 'US', name: { en: 'United States', ja: 'アメリカ', zh: '美国', ko: '미국', es: 'Estados Unidos', fr: 'États-Unis', de: 'USA', pt: 'EUA', ru: 'США', ar: 'الولايات المتحدة' } },
  { code: 'UY', name: { en: 'Uruguay', ja: 'ウルグアイ', zh: '乌拉圭', ko: '우루과이', es: 'Uruguay', fr: 'Uruguay', de: 'Uruguay', pt: 'Uruguai', ru: 'Уругвай', ar: 'أوروغواي' } },
  { code: 'UZ', name: { en: 'Uzbekistan', ja: 'ウズベキスタン', zh: '乌兹别克斯坦', ko: '우즈베키스탄', es: 'Uzbekistán', fr: 'Ouzbékistan', de: 'Usbekistan', pt: 'Uzbequistão', ru: 'Узбекистан', ar: 'أوزبكستان' } },
  { code: 'VU', name: { en: 'Vanuatu', ja: 'バヌアツ', zh: '瓦努阿图', ko: '바누아투', es: 'Vanuatu', fr: 'Vanuatu', de: 'Vanuatu', pt: 'Vanuatu', ru: 'Вануату', ar: 'فانواتو' } },
  { code: 'VE', name: { en: 'Venezuela', ja: 'ベネズエラ', zh: '委内瑞拉', ko: '베네수엘라', es: 'Venezuela', fr: 'Venezuela', de: 'Venezuela', pt: 'Venezuela', ru: 'Венесуэла', ar: 'فنزويلا' } },
  { code: 'VN', name: { en: 'Vietnam', ja: 'ベトナム', zh: '越南', ko: '베트남', es: 'Vietnam', fr: 'Viêt Nam', de: 'Vietnam', pt: 'Vietname', ru: 'Вьетнам', ar: 'فيتنام' } },
  { code: 'YE', name: { en: 'Yemen', ja: 'イエメン', zh: '也门', ko: '예멘', es: 'Yemen', fr: 'Yémen', de: 'Jemen', pt: 'Iémen', ru: 'Йемен', ar: 'اليمن' } },
  { code: 'ZM', name: { en: 'Zambia', ja: 'ザンビア', zh: '赞比亚', ko: '잠비아', es: 'Zambia', fr: 'Zambie', de: 'Sambia', pt: 'Zâmbia', ru: 'Замбия', ar: 'زامبيا' } },
  { code: 'ZW', name: { en: 'Zimbabwe', ja: 'ジンバブエ', zh: '津巴布韦', ko: '짐바브웨', es: 'Zimbabue', fr: 'Zimbabwe', de: 'Simbabwe', pt: 'Zimbábue', ru: 'Зимбабве', ar: 'زيمبابوي' } },
  { code: 'TW', name: { en: 'Taiwan', ja: '台湾', zh: '台湾', ko: '대만', es: 'Taiwán', fr: 'Taïwan', de: 'Taiwan', pt: 'Taiwan', ru: 'Тайвань', ar: 'تايوان' } },
]

export function getCountryName(code: string, locale: string): string {
  const country = countries.find(c => c.code === code)
  return country?.name[locale] || country?.name.en || code
}
